2018-02-10 23:05:31,828 INFO: Microblog startup 
 		 [in E:\Python Course\flask\pehlaFlask\app\__init__.py:49]
2018-02-11 00:23:47,535 INFO: Microblog startup 
 		 [in E:\Python Course\flask\pehlaFlask\app\__init__.py:49]
2018-02-11 00:24:35,846 INFO: Microblog startup 
 		 [in E:\Python Course\flask\pehlaFlask\app\__init__.py:49]
2018-02-11 00:33:28,604 INFO: Microblog startup 
 		 [in E:\Python Course\flask\pehlaFlask\app\__init__.py:49]
2018-02-11 00:46:52,904 INFO: Microblog startup 
 		 [in E:\Python Course\flask\pehlaFlask\app\__init__.py:49]
2018-02-11 00:47:59,557 ERROR: Exception on /follow/lordkingping [GET] 
 		 [in e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "E:\Python Course\flask\pehlaFlask\app\routes.py", line 150, in follow
    return redirect(url_for('user', username=username))
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\helpers.py", line 323, in url_for
    force_external=external)
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'user_profile' instead?
2018-02-11 00:50:25,824 INFO: Microblog startup 
 		 [in E:\Python Course\flask\pehlaFlask\app\__init__.py:49]
2018-02-11 02:04:55,843 INFO: Microblog startup 
 		 [in E:\Python Course\flask\pehlaFlask\app\__init__.py:49]
2018-02-11 02:05:07,769 ERROR: Exception on /user/sanskarssh [GET] 
 		 [in e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "E:\Python Course\flask\pehlaFlask\app\routes.py", line 75, in user_profile
    return render_template("user_profile.html", user = user_obj, posts = posts)
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "E:\Python Course\flask\pehlaFlask\app\templates\user_profile.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "E:\Python Course\flask\pehlaFlask\app\templates\base.html", line 34, in top-level template code
    {% block content %}{% endblock %}
  File "E:\Python Course\flask\pehlaFlask\app\templates\user_profile.html", line 26, in block "content"
    {% include "_post.html" %}
  File "E:\Python Course\flask\pehlaFlask\app\templates\_post.html", line 5, in top-level template code
    <a href="{{ url_for('user', username=post.author.username) }}">{{ post.author.username }}
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\helpers.py", line 323, in url_for
    force_external=external)
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'user_profile' instead?
2018-02-11 02:05:56,402 INFO: Microblog startup 
 		 [in E:\Python Course\flask\pehlaFlask\app\__init__.py:49]
2018-02-11 02:06:46,069 ERROR: Exception on /index [POST] 
 		 [in e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "E:\Python Course\flask\pehlaFlask\app\routes.py", line 19, in index
    db.session.add(post)
NameError: name 'db' is not defined
2018-02-11 02:07:26,597 INFO: Microblog startup 
 		 [in E:\Python Course\flask\pehlaFlask\app\__init__.py:49]
2018-02-11 02:48:08,037 INFO: Microblog startup 
 		 [in E:\Python Course\flask\pehlaFlask\app\__init__.py:49]
2018-02-11 03:09:17,275 INFO: Microblog startup 
 		 [in E:\Python Course\flask\pehlaFlask\app\__init__.py:49]
