2018-02-11 03:10:16,688 ERROR: Exception on /user/demo_acc_one [GET] 
 		 [in e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "e:\python course\flask\pehlaflask\pehla_virtualenv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "E:\Python Course\flask\pehlaFlask\app\routes.py", line 80, in user_profile
    page, app.config['POSTS_PER_PAGE'], False)
NameError: name 'app' is not defined
2018-02-11 03:11:12,445 INFO: Microblog startup 
 		 [in E:\Python Course\flask\pehlaFlask\app\__init__.py:49]
2018-02-11 03:13:23,619 INFO: Microblog startup 
 		 [in E:\Python Course\flask\pehlaFlask\app\__init__.py:49]
